# Ejercicio 38
Obtenga la matriz de correlación para saber idiomas distintos considerando que un
usuario sabe un idioma si indicó un nivel de 1 o superior

In [1]:
import pandas as pd

In [2]:
languages = pd.read_csv('wikipedia_dataset-2c2021/languages.csv')

In [3]:
languages.head()

   babel_user babel_lang babel_level
0     4502458         FR           2
1     5928200         aa           0
2       46918         ab           0
3     2050449         ab           1
4     4715583        ace           0

In [4]:
languages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35666 entries, 0 to 35665
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   babel_user   35666 non-null  int64
 1   babel_lang   35662 non-null  object
 2   babel_level  35666 non-null  object
dtypes: int64(1), object(2)
memory usage: 836.0+ KB

In [5]:
languages['babel_lang'].hasnans

True

In [6]:
babelLangFillna=languages['babel_lang'].fillna('NaN')
filtroBabelLangNa=babelLangFillna == 'NaN'
languagesNans=languages[filtroBabelLangNa]
languagesNans

       babel_user babel_lang babel_level
32096      739010        NaN           0
32097     5928200        NaN           0
32098      177135        NaN           2
32099      289278        NaN           N

In [7]:
languages=languages.dropna()

In [8]:
languages.isna().sum()

babel_user     0
babel_lang     0
babel_level    0
dtype: int64

In [9]:
languages = languages[languages['babel_level']!='0']

In [10]:
languages

       babel_user  babel_lang babel_level
0         4502458          FR           2
3         2050449          ab           1
6         4494742         acf           1
8           70090          af           1
9          407454          af           1
...           ...         ...         ...
35659     5915818  zh-Hans-CN           N
35660     2089885     zh-Hant           4
35661     2089885  zh-Hant-HK           1
35662     2089885  zh-Hant-TW           3
35665       87482         zza           N

[34572 rows x 3 columns]

In [11]:
languages['babel_level'].value_counts()

N    11533
1     7589
2     6452
3     5850
4     2504
5      644
Name: babel_level, dtype: int64

In [12]:
grouped_usrs = languages.sort_values('babel_user')

In [13]:
grouped_usrs

       babel_user babel_lang babel_level
27802          30         fr           N
35465          30         zh           1
29078          30         it           1
32586          30         pt           1
4731           30         en           2
...           ...        ...         ...
34032     6331490         pt           5
13359     6331490         en           N
14601     6331490         es           2
12851     6332447         en           5
24104     6332447         es           N

[34572 rows x 3 columns]

In [14]:
grouped_usrs['knows_lang'] = True

In [15]:
grouped_usrs.head(10)

       babel_user babel_lang babel_level  knows_lang
27802          30         fr           N        True
35465          30         zh           1        True
29078          30         it           1        True
32586          30         pt           1        True
4731           30         en           2        True
32133          30         nl           1        True
30876          30         ja           1        True
14602          30         es           3        True
2112           30         de           1        True
7433           38         en           3        True

In [16]:
pivot_grouped = grouped_usrs.pivot(index='babel_user',columns='babel_lang',values='knows_lang')
pivot_grouped = pivot_grouped.fillna(False)

In [17]:
pivot_grouped

babel_lang,FR,ab,acf,af,agr,akk,aln,am,an,ang,...,yue,zap,zea,zh,zh-Hans,zh-Hans-CN,zh-Hant,zh-Hant-HK,zh-Hant-TW,zza
babel_user,,,,,,,,,,,,,,,,,,,,,
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
262,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
267,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
294,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6318249,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6327193,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6327824,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6331490,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6332447,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Resultado

In [22]:
lang_corr = pivot_grouped.corr('pearson')
lang_corr

babel_lang,FR,ab,acf,af,agr,akk,aln,am,an,ang,...,yue,zap,zea,zh,zh-Hans,zh-Hans-CN,zh-Hant,zh-Hant-HK,zh-Hant-TW,zza
babel_lang,,,,,,,,,,,,,,,,,,,,,
FR,1.000000,-0.000093,-0.000093,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,-0.000278,-0.000093,-0.000093,-0.001290,-0.000093,-0.000160,-0.000093,-0.000093,-0.000093,-0.000093
ab,-0.000093,1.000000,-0.000093,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,-0.000278,-0.000093,-0.000093,-0.001290,-0.000093,-0.000160,-0.000093,-0.000093,-0.000093,-0.000093
acf,-0.000093,-0.000093,1.000000,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,-0.000278,-0.000093,-0.000093,-0.001290,-0.000093,-0.000160,-0.000093,-0.000093,-0.000093,-0.000093
af,-0.000293,-0.000293,-0.000293,1.000000,-0.000293,-0.000293,-0.000414,-0.000414,-0.002216,-0.000717,...,-0.000878,-0.000293,-0.000293,-0.004081,-0.000293,-0.000507,-0.000293,-0.000293,-0.000293,-0.000293
agr,-0.000093,-0.000093,-0.000093,-0.000293,1.000000,1.000000,-0.000131,-0.000131,-0.000700,-0.000227,...,-0.000278,-0.000093,-0.000093,0.071719,-0.000093,-0.000160,-0.000093,-0.000093,-0.000093,-0.000093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zh-Hans-CN,-0.000160,-0.000160,-0.000160,-0.000507,-0.000160,-0.000160,-0.000227,-0.000227,-0.001213,-0.000393,...,0.192076,-0.000160,-0.000160,0.082076,0.577297,1.000000,0.577297,0.577297,0.577297,-0.000160
zh-Hant,-0.000093,-0.000093,-0.000093,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,0.333210,-0.000093,-0.000093,0.071719,1.000000,0.577297,1.000000,1.000000,1.000000,-0.000093
zh-Hant-HK,-0.000093,-0.000093,-0.000093,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,0.333210,-0.000093,-0.000093,0.071719,1.000000,0.577297,1.000000,1.000000,1.000000,-0.000093
zh-Hant-TW,-0.000093,-0.000093,-0.000093,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,0.333210,-0.000093,-0.000093,0.071719,1.000000,0.577297,1.000000,1.000000,1.000000,-0.000093
zza,-0.000093,-0.000093,-0.000093,-0.000293,-0.000093,-0.000093,-0.000131,-0.000131,-0.000700,-0.000227,...,-0.000278,-0.000093,-0.000093,-0.001290,-0.000093,-0.000160,-0.000093,-0.000093,-0.000093,1.000000