# Ejercicio 44
Si decimos que la ubicación de un usuario es el promedio de la latitud y longitud de los contenidos geolocalizados para los cuales editó la última versión (ignorar usuarios que no editaron contenido geolocalizado). ¿Cuáles son los dos usuarios más cercanos?

In [1]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

In [2]:
df_geotags = pd.read_csv('wikipedia_dataset-2c2021/geo_tags.csv')
df_contents = pd.read_csv('wikipedia_dataset-2c2021/contents.csv')

In [3]:
merged_df = pd.merge(left=df_contents,right=df_geotags,left_on='id',right_on='gt_page_id',how='inner')

In [4]:
merged_df

,title,id,namespace,revision_id,parent_revision,revision_timestamp,revisor_username,revisor_id,revisor_ip,revisor_comment,...,gt_page_id,gt_globe,gt_primary,gt_lat,gt_lon,gt_dim,gt_type,gt_name,gt_country,gt_region
0,Andorra,7,0,138035057,138027475.0,2021-08-31T18:27:01Z,NaN,NaN,2800:CD0:FC1B:A900:C5A4:9E81:7175:2ED2,Añadir contenido,...,7,earth,0,42.500000,1.500000,10000,city,NaN,NaN,NaN
1,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,...,10,earth,0,-34.599722,-58.381944,10000,city,NaN,NaN,NaN
2,Geografía de Andorra,15,0,137986788,133666383.0,2021-08-29T17:16:00Z,Lojwe,5338508.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,...,15,earth,1,42.506111,1.522222,1000,landmark,NaN,NaN,NaN
3,Anoeta,26,0,133531913,125347732.0,2021-02-25T18:09:01Z,InternetArchiveBot,4704851.0,NaN,Rescatando 1 referencia(s) y marcando 0 enlace...,...,26,earth,1,43.162222,-2.070000,10000,city,NaN,NaN,NaN
4,Afganistán,39,0,138047554,138043235.0,2021-09-01T05:01:16Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,...,39,earth,0,34.532778,69.165833,10000,city,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537300,Kumarghat,10010550,0,138051050,138051042.0,2021-09-01T10:28:24Z,Carlukas,86975.0,NaN,Añadiendo la [[Categoría:Localidades de Tripur...,...,10010550,earth,1,24.158333,92.029722,10000,city,NaN,NaN,NaN
537301,Río Makarora,10010559,0,138051210,138051186.0,2021-09-01T10:45:37Z,Lorito987,5952489.0,NaN,NaN,...,10010559,earth,1,-44.316667,169.166667,1000,landmark,NaN,NaN,NaN
537302,Panisagar,10010567,0,138051314,138051311.0,2021-09-01T10:58:51Z,Carlukas,86975.0,NaN,Añadiendo la [[Categoría:Localidades de Tripur...,...,10010567,earth,1,24.250000,92.140000,10000,city,NaN,NaN,NaN
537303,Dewanpasa,10010581,0,138051603,138051596.0,2021-09-01T11:30:24Z,Carlukas,86975.0,NaN,Añadiendo la [[Categoría:Localidades de Tripur...,...,10010581,earth,1,24.360639,92.139850,10000,city,NaN,NaN,NaN
537304,Fatikroy,10010600,0,138051985,138051982.0,2021-09-01T12:03:14Z,Carlukas,86975.0,NaN,Añadiendo la [[Categoría:Localidades de Tripur...,...,10010600,earth,1,24.010639,92.001289,10000,city,NaN,NaN,NaN

In [5]:
allRevisors = merged_df['revisor_ip'].fillna(merged_df['revisor_username'])
allRevisors

0         2800:CD0:FC1B:A900:C5A4:9E81:7175:2ED2
1                                      Traitrich
2                                          Lojwe
3                             InternetArchiveBot
4                                      Traitrich
                           ...
537300                                  Carlukas
537301                                 Lorito987
537302                                  Carlukas
537303                                  Carlukas
537304                                  Carlukas
Name: revisor_ip, Length: 537305, dtype: object

In [6]:
merged_df['users_or_ip'] = allRevisors
merged_df.head()

,title,id,namespace,revision_id,parent_revision,revision_timestamp,revisor_username,revisor_id,revisor_ip,revisor_comment,...,gt_globe,gt_primary,gt_lat,gt_lon,gt_dim,gt_type,gt_name,gt_country,gt_region,users_or_ip
0,Andorra,7,0,138035057,138027475.0,2021-08-31T18:27:01Z,NaN,NaN,2800:CD0:FC1B:A900:C5A4:9E81:7175:2ED2,Añadir contenido,...,earth,0,42.500000,1.500000,10000,city,NaN,NaN,NaN,2800:CD0:FC1B:A900:C5A4:9E81:7175:2ED2
1,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,...,earth,0,-34.599722,-58.381944,10000,city,NaN,NaN,NaN,Traitrich
2,Geografía de Andorra,15,0,137986788,133666383.0,2021-08-29T17:16:00Z,Lojwe,5338508.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,...,earth,1,42.506111,1.522222,1000,landmark,NaN,NaN,NaN,Lojwe
3,Anoeta,26,0,133531913,125347732.0,2021-02-25T18:09:01Z,InternetArchiveBot,4704851.0,NaN,Rescatando 1 referencia(s) y marcando 0 enlace...,...,earth,1,43.162222,-2.070000,10000,city,NaN,NaN,NaN,InternetArchiveBot
4,Afganistán,39,0,138047554,138043235.0,2021-09-01T05:01:16Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,...,earth,0,34.532778,69.165833,10000,city,NaN,NaN,NaN,Traitrich

In [7]:
grouped_df = merged_df.groupby('users_or_ip').agg({'gt_lat':'mean','gt_lon':'mean'}).reset_index()
grouped_df.head()

  users_or_ip     gt_lat     gt_lon
0   "BF CLUB"  46.733439  22.023909
1  &beer&love  30.788290  -0.431666
2      (SVPG) -12.067886 -77.038516
3       -jem-  37.138333   7.382305
4     -sasha-  38.786371  -9.267020

In [8]:
grouped_df.isna().sum()

users_or_ip    0
gt_lat         0
gt_lon         0
dtype: int64

In [9]:
buscador = NearestNeighbors()
buscador.fit(grouped_df[['gt_lat', 'gt_lon']].values)

NearestNeighbors()

In [10]:
dist_minima = float('inf')
for usuario,lat,lon in zip(grouped_df['users_or_ip'],grouped_df['gt_lat'],grouped_df['gt_lon']):
    dist,index = buscador.kneighbors([[lat,lon]], n_neighbors=2)
    if dist_minima > dist.flatten()[1] and dist.flatten()[1] > 0:
        usuario1 = usuario
        usuario2 = grouped_df.loc[index.flatten()[1],'users_or_ip']
        dist_minima = dist.flatten()[1]

In [11]:
usuario1

'181.9.147.212'

In [12]:
usuario2

'JuliánDelRusso'

In [13]:
dist_minima

7.071063372632382e-09

## Resultado

In [14]:
print("%s y %s son los usuarios más cercanos con una distancia de"%(usuario1,usuario2),dist_minima)

181.9.147.212 y JuliánDelRusso son los usuarios más cercanos con una distancia de 7.071063372632382e-09